### ISSUE TITLE
Can not load topography data of nanonis

### ISSUE THREAD

**Issue by SatoAku** [yuksk/SIDAM#36]
When I load STM topography data of nanonis(.sxm file), igor 8 shows "ConvertTextEncoding gave error : Unknown text encoding" and I cannot open the topography data.
It can be caused by character code. My pc uses UTF-8.

**Comment by yuksk** [comment]
This error occurs when `DefaultTextEncoding` of Igor Pro returns `V_defaultTextEncoding=0`. There are two ways to solve this problem.

(1) Choose the text encoding used by the Nanonis software (likely UTF-8 in your case) from _Menubar > Misc > Text Encoding > Default Text Encoding_

This changes the default text encoding of Igor Pro and may influence other experiment files. Another way is

(2) Change `text_encoding = ""` in `SIDAM.default.toml` to `text_encoding = "UTF-8"` , and save it as written in `SIDAM.default.toml`. The file is under `Igor Pro 9 User Files\User Procedures\SIDAM\` . If you do not know where `Igor Pro 9 User Files` is, see how to [install](https://github.com/yuksk/SIDAM#user-content-install).

If you do not know what happens when you change the default text encoding of Igor Pro, the second way is better.
