### ISSUE TITLE
R≠0のときのXY座標がNanonisと異なる

### ISSUE THREAD

**Issue by YasuiYuuki** [yuksk/SIDAM#38]
NanonisのScan ControlでAngleが0 deg以外でトポグラフを取得したときに、Nanonis上でのXY座標とSIDAMでIgorに読み込んだsxmデータのXY座標が異なっているようです。
Bias spectroscopyで取得したデータのトポグラフでの位置を確認できるようになるとうれしいです。

**Comment by yuksk** [comment]
(English translation)
When an sxm file is loaded by SIDAM, the XY coordinates of the wave are different from those shown on the Nanonis software. This problem seems to happen when the angle in the Scan Control of Nanonis is not 0. It would be nice to check the position of the data acquired by Bias spectroscopy in a topograph.
