### ISSUE TITLE
There is no longer a color table under the offset box in the information bar of the graph

### ISSUE THREAD

**Issue by suyanyulong** [yuksk/SIDAM#40]
After V9.7.0, Click the icon ☰ to show the menu instead of right-clicking the control bar. But now the offset box doesn't contain the color table. How can I modify the color of graph?
![before](https://user-images.githubusercontent.com/32784382/206698424-b96eea02-28b4-4530-aa39-13b22878ad6c.png)
![now](https://user-images.githubusercontent.com/32784382/206699146-16e11736-d7fe-4e27-bb9e-d92cc41572ab.png)

**Comment by yuksk** [comment]
Thanks for your question clarifying the change. Igor's default function, `Menubar > Graph > Modify Trace Appearance,` can be used for a single color. The SIDAM function to apply a color table has been obsoleted. This is because it is not worth the time it would take to write functions and GUI panels that integrate both Igor's color tables and imported ones to apply a color table to traces.
